language: ruby
bundler_args: --without development console
before_install: ./extras/ci/setup.sh
before_script: bundle exec rake db:migrate && bundle exec rake db:migrate

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: 1.9.3

branches:
  only:
    - develop
notifications:
  irc: "irc.freenode.org#theforeman"
  email: false
  template:
    - "[#%{build_number}] %{message} %{build_url}"
    - "[#%{build_number}] %{commit} on %{branch} by %{author}"
    - "[#%{build_number}] %{compare_url}"
   on_success: always
   on_failure: always
   use_notice: false
