--- 
#:modulepath: /etc/puppet/modules/
:tftppath: tftp/
#:rrd_report_url: report/
#:ldap: true
#your default puppet server - can be overridden in the host level
#if none specified, plain "puppet" will be used.
#:puppet_server: puppet
#:unattended: false
#use the following setting to override the default 30 minutes puppet run interval - value must be in minutes
#:puppet_interval: 60