name: Deploy Storybook

on:
  pull_request:
    paths:
      - '**.stories.js'

jobs:
  deploy_storybook:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        clean: false
    - name: Run npm install
      run: npm install
    - name: Build Storybook
      run: npm run build-storybook -- --output-dir=storybooks/${{ github['event']['pull_request']['number'] }}
    - name: Tell Github not to use jekyll
      run: touch .nojekyll
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Foreman Storybook Bot"
        git add .
        git status
        git commit -m "Storybook build for PR #${{ github['event']['pull_request']['number'] }}"
    - name: Deploy Storybook to gh-pages branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: gh-pages
    - name: Comment PR with new Storybook location
      if: success()
      uses: thollander/actions-comment-pull-request@master
      with:
        message: "Deployed the [Storybook](https://jeremylenz.github.io/foreman/storybooks/${{ github['event']['pull_request']['number'] }}) for this PR to the `gh-pages` branch."
        GITHUB_TOKEN: ${{ github.token }}
